In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf

In [5]:
dataset = pd.read_csv('sobar-72.csv')

In [6]:
dataset.head()

behavior_sexualRisk  behavior_eating  behavior_personalHygine  \
0                   10               13                       12   
1                   10               11                       11   
2                   10               15                        3   
3                   10               11                       10   
4                    8               11                        7   

   intention_aggregation  intention_commitment  attitude_consistency  \
0                      4                     7                     9   
1                     10                    14                     7   
2                      2                    14                     8   
3                     10                    15                     7   
4                      8                    10                     7   

   attitude_spontaneity  norm_significantPerson  norm_fulfillment  \
0                    10                       1                 8   
1                     7                       5                 5   
2                    10                       1                 4   
3                     7                       1                 5   
4                     8                       1                 5   

   perception_vulnerability  perception_severity  motivation_strength  \
0                         7                    3                   14   
1                         4                    2                   15   
2                         7                    2                    7   
3                         4                    2                   15   
4                         3                    2                   15   

   motivation_willingness  socialSupport_emotionality  \
0                       8                           5   
1                      13                           7   
2                       3                           3   
3                      13                           7   
4                       5                           3   

   socialSupport_appreciation  socialSupport_instrumental  \
0                           7                          12   
1                           6                           5   
2                           6                          11   
3                           4                           4   
4                           6                          12   

   empowerment_knowledge  empowerment_abilities  empowerment_desires  \
0                     12                     11                    8   
1                      5                      4                    4   
2                      3                      3                   15   
3                      4                      4                    4   
4                      5                      4                    7   

   ca_cervix  
0          1  
1          1  
2          1  
3          1  
4          1

In [7]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [8]:
X

array([[10, 13, 12, ..., 12, 11,  8],
       [10, 11, 11, ...,  5,  4,  4],
       [10, 15,  3, ...,  3,  3, 15],
       ...,
       [10,  8, 11, ..., 12, 10, 10],
       [ 9, 12, 13, ..., 11, 13, 15],
       [10, 14, 14, ..., 13, 15, 15]], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
X_train.shape

(57, 19)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [12]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
ann = tf.keras.models.Sequential()

In [14]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [15]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [16]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [17]:
ann.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

In [18]:
ann.fit(X_train,y_train,batch_size=32, epochs= 100)

Epoch 1/100
2/2 [==============================] - 0s 4ms/step - loss: 0.7844 - accuracy: 0.3860
Epoch 2/100
2/2 [==============================] - 0s 1ms/step - loss: 0.7776 - accuracy: 0.3860
Epoch 3/100
2/2 [==============================] - 0s 3ms/step - loss: 0.7711 - accuracy: 0.3860
Epoch 4/100
2/2 [==============================] - 0s 2ms/step - loss: 0.7649 - accuracy: 0.3860
Epoch 5/100
2/2 [==============================] - 0s 1ms/step - loss: 0.7587 - accuracy: 0.4035
Epoch 6/100
2/2 [==============================] - 0s 4ms/step - loss: 0.7531 - accuracy: 0.4035
Epoch 7/100
2/2 [==============================] - 0s 1ms/step - loss: 0.7471 - accuracy: 0.4035
Epoch 8/100
2/2 [==============================] - 0s 1ms/step - loss: 0.7415 - accuracy: 0.4035
Epoch 9/100
2/2 [==============================] - 0s 1ms/step - loss: 0.7353 - accuracy: 0.3860
Epoch 10/100
2/2 [==============================] - 0s 2ms/step - loss: 0.7295 - accuracy: 0.3860
Epoch 11/100
2/2 [===========

In [19]:
y_pred = ann.predict(X_test)

In [20]:
y_pred = (y_pred > 0.5)

In [21]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [23]:
cm = confusion_matrix(y_test, y_pred)

In [24]:
print(cm)

[[13  1]
 [ 0  1]]


In [25]:
accuracy_score(y_test,y_pred)

0.9333333333333333

In [26]:
[10,13,12,4,7,9,10,1,8,7,3,14,8,5,7,12,12,11,8]
# 1) behavior_eating
# 2) behavior_personalHygine
# 3) intention_aggregation
# 4) intention_commitment
# 5) attitude_consistency
# 6) attitude_spontaneity
# 7) norm_significantPerson
# 8) norm_fulfillment
# 9) perception_vulnerability
# 10) perception_severity
# 11) motivation_strength
# 12) motivation_willingness
# 13) socialSupport_emotionality
# 14) socialSupport_appreciation
# 15) socialSupport_instrumental
# 16) empowerment_knowledge
# 17) empowerment_abilities
# 18) empowerment_desires
# 19) ca_cervix (this is class attribute, 1=has cervical cancer, 0=no cervical cancer)

[10, 13, 12, 4, 7, 9, 10, 1, 8, 7, 3, 14, 8, 5, 7, 12, 12, 11, 8]

In [27]:
sc.transform([[10,13,12,4,7,9,10,1,8,7,3,14,8,5,7,12,12,11,8]])

array([[ 0.29816978,  0.10986137,  0.37679668, -1.30603394, -2.54485345,
         1.31487638,  0.95958476, -1.16354173, -0.12276208, -0.4093991 ,
        -0.7271421 ,  0.430497  , -0.3394056 , -0.61551952,  0.35646381,
         0.48764957,  0.49519088,  0.59862541, -0.34002987]])

In [28]:
ann.predict(sc.transform([[10,13,12,4,7,9,10,1,8,7,3,14,8,5,7,12,12,11,8]]))
# Predict the probability 
# ( This is why we use the Sigmoid activation at the output layer for binary classification)

array([[0.7105405]], dtype=float32)

In [34]:
print(ann.predict(sc.transform([[10,13,12,4,7,9,10,1,8,7,3,14,8,5,7,12,12,11,8]])) > 0.50)

[[ True]]
